[theme]

# Primary accent for interactive elements
primaryColor = '#00c2fb'

# Background color for the main content area
backgroundColor = '#13113c'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#13112D'

# Color used for almost all text
textColor = '#fff'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
[browser]
gatherUsageStats = false
